---
documentclass: scrbook
bibliography: ["./zotero.bib"]
csl: "apa.csl"
table-of-contents: true
link-citations: true
title: "Conversations with Computers"
lang: en-US
reference-location: document
linkReferences: true
nameInLink: true
colorlinks: true
papersize: b5
dpi: 300
resource-path: ["./Images/original/"] #Change this for full resolution images
header-includes: |
  \usepackage{enotez}
  \usepackage[multidot]{grffile}
  \setenotez{split=chapter, split-title={\thechapter}, reset=true, backref=true, totoc=chapter}
#  \let\footnote=\endnote

---
